Feature instagram widget
bits-and-bytes-association/bba-website-nextjs pull request #20
Opened 2023-08-05 17:23 UTC by milolucero

Responsive Instagram component with placeholder images.

Takes an array of URLs representing the hrefs of the Instagram images and displays the first 4 images of the array (3 in mobile view).

2023-08-20 02:26 UTC, bandrson requested changes
Overall it looks good but there's a couple minor issues which need to be addressed before merging. Please see the review comments.

2023-08-20 02:26 UTC, bandrson commented on src/components/InstagramWidget.js
> +  const instagramImages = [
Seems like these images are being accessed with a now expired token.

2023-08-20 02:26 UTC, bandrson commented on src/components/InstagramWidget.js
> +      <HeadingBBAStyle>{title}</HeadingBBAStyle>
For consistency with the other front page headings, please add the `cursor-default` Tailwind class. Inside the referenced component would probably be best.

2023-08-20 02:30 UTC, bandrson commented on src/components/InstagramWidget.js
> +  const instagramImages = [
I'd be completely fine with just using a placeholder icon from Heroicons to tide us over. (maybe `photo`)

2023-08-20 15:25 UTC, milolucero commented on src/components/InstagramWidget.js
> +  const instagramImages = [
To maintain the code so that it will just require an image source I've changed it to a placeholder image resembling a photo icon. Let me know if you would prefer something different here.

2023-08-20 15:31 UTC, milolucero commented
I have implemented the changes suggested, let me know if I missed something or if there is anything else you think we should modify.

2023-08-23 05:07 UTC, bandrson approved these changes

2023-08-23 05:10 UTC, bandrson commented
Looks good with the updates. I took the liberty of adding some hover effects.

2023-08-23 05:11 UTC, merged