Past executives page
bits-and-bytes-association/bba-website-nextjs pull request #22
Opened 2023-08-25 21:57 UTC by milolucero

Adds the Past Executives page with search functionality,

I considered a table layout as a better way to display this information compared to the previous accordion per term. I also developed a search bar to filter the displayed results. 

I considered removing the "Member at Large" from previous terms, but didn't feel comfortable removing names of whom I didn't know their contribution.

Maybe this section could have a different name, such as "Previous collaborators" or "Past team members", so that it is more clear that it does not only refer to the executive team. 

Feel free to make changes or let me know if there is anything you would like me to modify.

2023-08-25 22:20 UTC, bandrson commented
Looking good. Perhaps we should reach out to the current leadership team to pin down some criteria for making it onto this list as an "executive".

2023-08-25 22:25 UTC, bandrson requested changes

2023-08-25 22:25 UTC, bandrson commented on src/pages/past-executives/index.js
> +      const termOrder = {
Unless I'm mistaken, there's only 3 terms. Winter, spring, and fall.

2023-08-26 03:41 UTC, milolucero commented on src/pages/past-executives/index.js
> +      const termOrder = {
Oh my bad! I've removed the summer term option.

2023-08-26 03:46 UTC, milolucero commented
Agreed, maybe we can hand the question to the current leadership so that they can decide how it should be handled. For now I have solved the issue with the terms and the PR is ready to merge after you review and accept the requested change.

2023-08-26 03:50 UTC, bandrson approved these changes
Issue resolved. We can merge for now and I'll reach out to the leadership.

2023-08-26 03:51 UTC, merged